new change

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,12 +1,15 @@
 name: Deployment (Container)
+
 on:
   push:
     branches:
       - main
       - dev
+
 env:
   CACHE_KEY: node-deps
   MONGODB_DB_NAME: gha-demo
+
 jobs:
   test:
     environment: testing
@@ -20,26 +23,31 @@ jobs:
     steps:
       - name: Get Code
         uses: actions/checkout@v3
+
+      - name: Debug Files
+        run: ls -la
+
       - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ~/.npm
           key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
+
       - name: Install dependencies
         run: npm ci
+
+      - name: Verify dependencies
+        run: npm list body-parser || echo "❌ Missing dependencies!"
+
       - name: Show GitHub Actions Runner IP
         run: curl ifconfig.me
-      - name: Get Code
-        uses: actions/checkout@v3
-      - name: Debug environment variables
-        run: npm start
-      - name: Run server
-        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
+
+      - name: Start Server
+        run: npm start & npx wait-on http://127.0.0.1:$PORT
+
       - name: Run tests
         run: npm test
-      - name: Output information
-        run: |
-          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
+
   deploy:
     needs: test
     runs-on: ubuntu-latest
